server:
  port: 8080
  servlet:
    context-path: /

Spring:
  application:
    name£º base_ssh
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver